pipeline {
    agent any

    stages {
        stage('fetch') {
            steps {
                sh "mkdir -p src"
                sh "git clone https://github.com/Dawr82/Java-Algorithms.git ./src"
            }
        }
    }
}